[tool.poetry]
name = "maui-software"
version = "0.1.7"
description = "Eco-acoustics data visualization and analysis"
authors = ["Caio Ferreira Bernardo <caio.bernardo@usp.br>"]
readme = "README.md"

packages = [
    { include = "maui" }
]


[tool.poetry.dependencies]
python = ">=3.9,<3.13"
scikit-maad = "^1.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
